import { ArrowRight, Code2, Globe2, LayoutTemplate, MessageCircle, MonitorSmartphone, ShoppingCart, Wrench, CheckCircle2, Phone } from 'lucide-react'
import Header from '../components/Header'
import logo from '../assets/logo.png'
import { projects } from '../data'

/* WhatsApp de contacto (Portugal +351) */
const WHATSAPP_NUMBER='351963717020'
const WHATSAPP_DISPLAY='+351 963 717 020'
const WHATSAPP_URL=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent('Olá! Vim pelo site da Agência Goolbe e gostaria de solicitar um orçamento.')}`
const services=[
 [Globe2,'Websites profissionais','Sites institucionais modernos, rápidos e preparados para apresentar sua empresa com credibilidade.'],
 [LayoutTemplate,'Landing pages','Páginas objetivas para campanhas, captação de contactos, serviços e lançamentos.'],
 [ShoppingCart,'Lojas virtuais','Experiências de compra responsivas, organizadas e pensadas para facilitar suas vendas online.'],
 [Code2,'Sistemas web','Soluções personalizadas para automatizar processos e organizar a operação do seu negócio.'],
 [MonitorSmartphone,'Design responsivo','Interfaces que funcionam com excelência no computador, tablet e telemóvel.'],
 [Wrench,'Suporte e evolução','Manutenção, melhorias e acompanhamento para o seu projeto continuar evoluindo.']
]

const steps=[['01','Descoberta','Entendemos o negócio, o público e o objetivo do projeto.'],['02','Planeamento','Definimos estrutura, conteúdo, funcionalidades e direção visual.'],['03','Desenvolvimento','Transformamos o planeamento em uma experiência digital rápida e responsiva.'],['04','Publicação','Revisamos, colocamos no ar e deixamos tudo pronto para receber clientes.']]
export default function Home(){return <><Header/><main>
<section id="inicio" className="hero"><div className="heroGlow"></div><div className="container heroGrid"><div><span className="eyebrow">DESENVOLVIMENTO WEB & SOLUÇÕES DIGITAIS</span><h1>Sua empresa merece uma presença digital que <span>trabalha por ela.</span></h1><p>Criamos websites, landing pages, lojas virtuais e sistemas personalizados para transformar ideias em experiências digitais claras, modernas e profissionais.</p><div className="actions"><a className="btn" href="#contato">Solicitar orçamento <ArrowRight size={18}/></a><a className="btn ghost" href="#projetos">Conhecer projetos</a></div><div className="heroNotes"><span><CheckCircle2/> Atendimento personalizado</span><span><CheckCircle2/> Soluções sob medida</span></div></div><div className="heroVisual"><div className="logoCard"><img src={logo} alt="Agência Goolbe"/><span>Da ideia ao digital.</span></div><div className="heroBadges"><div className="floatCard f1">Sites responsivos</div><div className="floatCard f2">Experiências modernas</div></div></div></div></section>
<section id="servicos" className="section"><div className="container"><div className="sectionHead"><span className="eyebrow">O QUE FAZEMOS</span><h2>Soluções digitais para tirar sua ideia do papel.</h2><p>Do primeiro clique à gestão do negócio, desenvolvemos projetos pensados para a realidade de cada empresa.</p></div><div className="cards">{services.map(([Icon,title,text]:any)=><article className="service" key={title}><div className="icon"><Icon/></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section id="projetos" className="section projects"><div className="container"><div className="sectionHead row"><div><span className="eyebrow">PORTFÓLIO</span><h2>Projetos desenvolvidos</h2></div><p>Uma seleção de soluções digitais criadas para diferentes segmentos, com foco em presença profissional, experiência do usuário e identidade de cada negócio.</p></div><div className="projectGrid">{projects.map(project=><a className="projectCard" href={project.demoUrl} target="_blank" rel="noopener noreferrer" key={project.title}><div className="projectVisual"><img src={project.image} alt={`Projeto ${project.title}`}/><span className="projectCategory">{project.category}</span></div><div className="projectContent"><h3>{project.title}</h3><p>{project.description}</p><div className="projectTags">{project.tags.map(tag=><span key={tag}>{tag}</span>)}</div><span className="projectLink">Visualizar projeto ↗</span></div></a>)}</div></div></section>
<section id="processo" className="section dark"><div className="container"><div className="sectionHead light"><span className="eyebrow">NOSSO PROCESSO</span><h2>Um caminho simples da conversa à publicação.</h2></div><div className="steps">{steps.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section id="sobre" className="section"><div className="container about"><div className="aboutMark"><img src={logo} alt="Logo Agência Goolbe"/></div><div><span className="eyebrow">SOBRE A AGÊNCIA</span><h2>Tecnologia com propósito e proximidade.</h2><p>A Agência Goolbe desenvolve soluções digitais para pequenas e médias empresas que querem fortalecer sua presença online, vender, organizar processos ou transformar uma ideia em produto digital.</p><p>Trabalhamos com uma abordagem direta: entender o que o negócio realmente precisa e construir uma solução moderna, responsiva e fácil de usar.</p><a className="textLink" href="#contato">Vamos conversar sobre sua ideia <ArrowRight size={17}/></a></div></div></section>
<section id="contato" className="section contact"><div className="container contactBox"><div><span className="eyebrow">VAMOS CRIAR ALGO?</span><h2>Tem um projeto em mente?</h2><p>Conte o que sua empresa precisa. Podemos conversar sobre a ideia e encontrar a solução digital mais adequada.</p></div><div className="contactActions"><a className="btn white" href={WHATSAPP_URL} target="_blank" rel="noreferrer"><MessageCircle size={19}/> Falar pelo WhatsApp</a></div></div></section>
</main><footer><div className="container footer"><div className="footerBrand"><img src={logo} alt="Agência Goolbe"/><p>Websites e soluções digitais para empresas.</p></div><div className="footerLinks"><a href="#servicos">Serviços</a><a href="#projetos">Projetos</a><a href="#sobre">Sobre</a><a href="#contato">Contato</a></div><small>© 2026 Agência Goolbe. Todos os direitos reservados.</small></div></footer></>}
